### ISSUE TITLE
打开地址错误，git Parameter参数构建不显示

### ISSUE THREAD

**Issue by ucfjepl** [me10zyl/utools-jenkins#1]
![image](https://user-images.githubusercontent.com/11847554/98930790-14013b80-2518-11eb-827e-33ab9b030e2b.png)

点击项目名称时跳转到了本地地址：
![image](https://user-images.githubusercontent.com/11847554/98930837-29766580-2518-11eb-8c9b-e808ae58a5d5.png)

参数构建时，只显示了参数名称，没有显示分支
![image](https://user-images.githubusercontent.com/11847554/98930917-4ad75180-2518-11eb-9570-fd095039ac40.png)

**Comment by me10zyl** [comment]
127.0.0.1 好像是在jenkins上设的地址，反正跟jenkins有关系，好好看下jenkins配置呢。

**Comment by me10zyl** [comment]
这个参数是什么类型的参数，能在jenkins上截图一下吗

**Comment by ucfjepl** [comment]
> 这个参数是什么类型的参数，能在jenkins上截图一下吗

git参数配置，这个是截图：
![image](https://user-images.githubusercontent.com/11847554/102038117-611b4a80-3e01-11eb-93bd-be3253ddbf77.png)

**Comment by ucfjepl** [comment]
> 127.0.0.1 好像是在jenkins上设的地址，反正跟jenkins有关系，好好看下jenkins配置呢。

utools的jenkins插件中配置的是192.168.0.8的地址，但是在utools中点击项目名称，打开浏览器就是127.0.0.1的地址
![image](https://user-images.githubusercontent.com/11847554/102038471-5319f980-3e02-11eb-92d5-e31d30dcac1e.png)

**Comment by ucfjepl** [comment]
> 127.0.0.1 好像是在jenkins上设的地址，反正跟jenkins有关系，好好看下jenkins配置呢。

这个问题解决了，在jenkins中的系统配置-jenkins URL中改成局域网地址了，原来配置的127.0.0.1

**Comment by me10zyl** [comment]
git参数已支持
