### ISSUE TITLE
点击构建无反应

### ISSUE THREAD

**Issue by SmileLee123** [me10zyl/utools-jenkins#2]

**Comment by me10zyl** [comment]
是最新的v0.0.4版本吗，现在已经修复了，都能构建

**Comment by MikeWang-9527** [comment]
同样的问题,点击标题会在jenkins域名后加jenkins-on 导致访问不到对应地址

**Comment by me10zyl** [comment]
检查一下在jenkins中的系统配置中配置的jenkins地址是否正确

**Comment by SmileLee123** [comment]
版本 0.0.4

**Comment by SmileLee123** [comment]
版本 0.0.4
![Uploading image.png…]()

**Comment by SmileLee123** [comment]
版本是最新的v0.04,构建还是无反应

**Comment by me10zyl** [comment]
能提供一下jenkins 任务配置信息吗（如是否是参数构建？参数构建的类型（可截图）等等）

**Comment by SmileLee123** [comment]
![Uploading Snipaste_2021-01-07_13-46-36.png…]()

**Comment by SmileLee123** [comment]
![Snipaste_2021-01-07_13-46-36](https://user-images.githubusercontent.com/33251469/103856373-7e38f580-50ef-11eb-8368-00464308a7ca.png)
